version: "3.8"
services:
 client-dev:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "443:443"
  volumes:
   - .:/app
   - /app/node_modules
  env_file:
   - .env.local
 
 client-prod:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "80:80"
  env_file:
   - .env
  
  