import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState } from "react";
import Chat from "../components/Chat";

export default function Home() {
  const [flag, setflag] = useState(false);
  const handle= ()=>{setflag(true)};
  return (
    <>
      <Head>
        <title>AnoTalk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img className={styles.container} src="./bg.jpg" alt="" />
      
      <Chat/>
      {/* <div className={flag? styles.invisible : styles.container}>
      <img className={styles.logo} src="./AT-logo.png" alt="" />
        <div className={styles.inner1}>
          <h1 className={styles.title}>AnoTalk</h1>
          <h4 className={styles.about}>AnoTalk facilitates anonymous group chat sessions. It allows users to engage in real-time conversations without revealing their identities. </h4>
          <button className={styles.button} onClick={handle}>
            Enter Chatroom
          </button>
        </div>
        <div className={styles.inner2}>
        <img className={styles.image} src="./image.png" alt="" />

        </div>
      </div> */}
    </>
  );
}
